apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api
  namespace: job-monitoring
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "25m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - app.processzero.co.uk
      secretName: processzero-api-tls
  rules:
    - host: app.processzero.co.uk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 8110
