apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: job-monitoring
resources:
  - ../../base
  - ../../keda
  - ingress.yaml
images:
  - name: ghcr.io/your-org/job-website-monitoring-agent
    newName: ghcr.io/processzero/job-website-monitoring-agent
    newTag: latest
patches:
  - path: managed-services-config.patch.yaml
  - path: production-replicas.patch.yaml
